"""Init

Revision ID: b4c4fab2feef
Revises: deb92f04f738
Create Date: 2023-10-29 20:25:53.777304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c4fab2feef'
down_revision = 'deb92f04f738'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('discipline', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'discipline')
    # ### end Alembic commands ###
